package classesFactura;
// Generated 20/01/2016 13:49:47 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Article generated by hbm2java
 */
public class Article implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String codA;
	private String descrip;
	private BigDecimal preu;
	private Short stock;
	private Short stockMin;
	private Set<LiniaFac> liniaFacs = new HashSet<LiniaFac>(0);

	public Article() {
	}

	public Article(String codA) {
		this.codA = codA;
	}

	public Article(String codA, String descrip, BigDecimal preu, Short stock, Short stockMin, Set<LiniaFac> liniaFacs) {
		this.codA = codA;
		this.descrip = descrip;
		this.preu = preu;
		this.stock = stock;
		this.stockMin = stockMin;
		this.liniaFacs = liniaFacs;
	}

	public String getCodA() {
		return this.codA;
	}

	public void setCodA(String codA) {
		this.codA = codA;
	}

	public String getDescrip() {
		return this.descrip;
	}

	public void setDescrip(String descrip) {
		this.descrip = descrip;
	}

	public BigDecimal getPreu() {
		return this.preu;
	}

	public void setPreu(BigDecimal preu) {
		this.preu = preu;
	}

	public Short getStock() {
		return this.stock;
	}

	public void setStock(Short stock) {
		this.stock = stock;
	}

	public Short getStockMin() {
		return this.stockMin;
	}

	public void setStockMin(Short stockMin) {
		this.stockMin = stockMin;
	}

	public Set<LiniaFac> getLiniaFacs() {
		return this.liniaFacs;
	}

	public void setLiniaFacs(Set<LiniaFac> liniaFacs) {
		this.liniaFacs = liniaFacs;
	}

}
