package classesFactura;
// Generated 20/01/2016 13:49:47 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
public class Client implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int codCli;
	private Poble poble;
	private String nom;
	private String adreca;
	private Integer cp;
	private Set<Factura> facturas = new HashSet<Factura>(0);

	public Client() {
	}

	public Client(int codCli) {
		this.codCli = codCli;
	}

	public Client(int codCli, Poble poble, String nom, String adreca, Integer cp, Set<Factura> facturas) {
		this.codCli = codCli;
		this.poble = poble;
		this.nom = nom;
		this.adreca = adreca;
		this.cp = cp;
		this.facturas = facturas;
	}

	public int getCodCli() {
		return this.codCli;
	}

	public void setCodCli(int codCli) {
		this.codCli = codCli;
	}

	public Poble getPoble() {
		return this.poble;
	}

	public void setPoble(Poble poble) {
		this.poble = poble;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getAdreca() {
		return this.adreca;
	}

	public void setAdreca(String adreca) {
		this.adreca = adreca;
	}

	public Integer getCp() {
		return this.cp;
	}

	public void setCp(Integer cp) {
		this.cp = cp;
	}

	public Set<Factura> getFacturas() {
		return this.facturas;
	}

	public void setFacturas(Set<Factura> facturas) {
		this.facturas = facturas;
	}

}
