package classesVideoClub;
// Generated 14/06/2016 10:00:33 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Lloguer generated by hbm2java
 */
public class Lloguer implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int NLlog;
	private PelLicula pelLicula;
	private Client client;
	private Date dataP;
	private Integer durada;
	private Date dataT;

	public Lloguer() {
	}

	public Lloguer(int NLlog) {
		this.NLlog = NLlog;
	}

	public Lloguer(int NLlog, PelLicula pelLicula, Client client, Date dataP, Integer durada, Date dataT) {
		this.NLlog = NLlog;
		this.pelLicula = pelLicula;
		this.client = client;
		this.dataP = dataP;
		this.durada = durada;
		this.dataT = dataT;
	}

	public int getNLlog() {
		return this.NLlog;
	}

	public void setNLlog(int NLlog) {
		this.NLlog = NLlog;
	}

	public PelLicula getPelLicula() {
		return this.pelLicula;
	}

	public void setPelLicula(PelLicula pelLicula) {
		this.pelLicula = pelLicula;
	}

	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	public Date getDataP() {
		return this.dataP;
	}

	public void setDataP(Date dataP) {
		this.dataP = dataP;
	}

	public Integer getDurada() {
		return this.durada;
	}

	public void setDurada(Integer durada) {
		this.durada = durada;
	}

	public Date getDataT() {
		return this.dataT;
	}

	public void setDataT(Date dataT) {
		this.dataT = dataT;
	}

}
