package classesVideoClub;
// Generated 14-jun-2016 18:16:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private String dni;
     private String nom;
     private String telefon;
     private String adreca;
     private String poblacio;
     private Set lloguers = new HashSet(0);

    public Client() {
    }

	
    public Client(String dni) {
        this.dni = dni;
    }
    public Client(String dni, String nom, String telefon, String adreca, String poblacio, Set lloguers) {
       this.dni = dni;
       this.nom = nom;
       this.telefon = telefon;
       this.adreca = adreca;
       this.poblacio = poblacio;
       this.lloguers = lloguers;
    }
   
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getTelefon() {
        return this.telefon;
    }
    
    public void setTelefon(String telefon) {
        this.telefon = telefon;
    }
    public String getAdreca() {
        return this.adreca;
    }
    
    public void setAdreca(String adreca) {
        this.adreca = adreca;
    }
    public String getPoblacio() {
        return this.poblacio;
    }
    
    public void setPoblacio(String poblacio) {
        this.poblacio = poblacio;
    }
    public Set getLloguers() {
        return this.lloguers;
    }
    
    public void setLloguers(Set lloguers) {
        this.lloguers = lloguers;
    }




}


