package classesVideoClub;
// Generated 14-jun-2016 18:16:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PelLicula generated by hbm2java
 */
public class PelLicula  implements java.io.Serializable {


     private int codP;
     private Productora productora;
     private String titol;
     private Integer numEx;
     private String director;
     private Integer numDisp;
     private Set lloguers = new HashSet(0);

    public PelLicula() {
    }

	
    public PelLicula(int codP) {
        this.codP = codP;
    }
    public PelLicula(int codP, Productora productora, String titol, Integer numEx, String director, Integer numDisp, Set lloguers) {
       this.codP = codP;
       this.productora = productora;
       this.titol = titol;
       this.numEx = numEx;
       this.director = director;
       this.numDisp = numDisp;
       this.lloguers = lloguers;
    }
   
    public int getCodP() {
        return this.codP;
    }
    
    public void setCodP(int codP) {
        this.codP = codP;
    }
    public Productora getProductora() {
        return this.productora;
    }
    
    public void setProductora(Productora productora) {
        this.productora = productora;
    }
    public String getTitol() {
        return this.titol;
    }
    
    public void setTitol(String titol) {
        this.titol = titol;
    }
    public Integer getNumEx() {
        return this.numEx;
    }
    
    public void setNumEx(Integer numEx) {
        this.numEx = numEx;
    }
    public String getDirector() {
        return this.director;
    }
    
    public void setDirector(String director) {
        this.director = director;
    }
    public Integer getNumDisp() {
        return this.numDisp;
    }
    
    public void setNumDisp(Integer numDisp) {
        this.numDisp = numDisp;
    }
    public Set getLloguers() {
        return this.lloguers;
    }
    
    public void setLloguers(Set lloguers) {
        this.lloguers = lloguers;
    }




}


