package classesVideoClub;
// Generated 14-jun-2016 18:16:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Productora generated by hbm2java
 */
public class Productora  implements java.io.Serializable {


     private String codPr;
     private String nom;
     private String nacio;
     private String seu;
     private Set pelLiculas = new HashSet(0);

    public Productora() {
    }

	
    public Productora(String codPr) {
        this.codPr = codPr;
    }
    public Productora(String codPr, String nom, String nacio, String seu, Set pelLiculas) {
       this.codPr = codPr;
       this.nom = nom;
       this.nacio = nacio;
       this.seu = seu;
       this.pelLiculas = pelLiculas;
    }
   
    public String getCodPr() {
        return this.codPr;
    }
    
    public void setCodPr(String codPr) {
        this.codPr = codPr;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getNacio() {
        return this.nacio;
    }
    
    public void setNacio(String nacio) {
        this.nacio = nacio;
    }
    public String getSeu() {
        return this.seu;
    }
    
    public void setSeu(String seu) {
        this.seu = seu;
    }
    public Set getPelLiculas() {
        return this.pelLiculas;
    }
    
    public void setPelLiculas(Set pelLiculas) {
        this.pelLiculas = pelLiculas;
    }




}


